# Generated by Django 3.0.4 on 2020-04-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=6000)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('zip_code', models.CharField(max_length=120)),
                ('phone', models.CharField(default='', max_length=120)),
            ],
        ),
    ]
